// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IdscH3Tj63X0v4w2jjLJSiGvMn9kyFo',
    appId: '1:586818569165:web:c39a6632ab2a4c2e12ba84',
    messagingSenderId: '586818569165',
    projectId: 'examen-final-futta',
    authDomain: 'examen-final-futta.firebaseapp.com',
    storageBucket: 'examen-final-futta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWv8ib1aoeXXjGumM8ZR3Ygdtw7HUa_UI',
    appId: '1:586818569165:android:4299c4577fc647b912ba84',
    messagingSenderId: '586818569165',
    projectId: 'examen-final-futta',
    storageBucket: 'examen-final-futta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjjCl0_7uA4gMVDLTS42zqXKfFuPVuI8',
    appId: '1:586818569165:ios:57d6268b35621cbe12ba84',
    messagingSenderId: '586818569165',
    projectId: 'examen-final-futta',
    storageBucket: 'examen-final-futta.appspot.com',
    iosClientId: '586818569165-5fnbt8crnpvhav2dkraarm9jns68v3vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjjCl0_7uA4gMVDLTS42zqXKfFuPVuI8',
    appId: '1:586818569165:ios:57d6268b35621cbe12ba84',
    messagingSenderId: '586818569165',
    projectId: 'examen-final-futta',
    storageBucket: 'examen-final-futta.appspot.com',
    iosClientId: '586818569165-5fnbt8crnpvhav2dkraarm9jns68v3vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.examenFinal',
  );
}
